name: trading_sunday_poland
description: Library to allow checking if there is trading sunday in poland
version: 1.0.0
repository: https://github.com/KopaczPatryk/trading_sunday_poland

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  lints: ^2.0.0

dev_dependencies:
  test: ^1.24.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
