name: trading_sunday_poland
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  lints: 4.0.0

dev_dependencies:
  test: ^1.24.0
